language: node_js
node_js:
  - "0.12"
script:
  - npm install coveralls --save-dev
after_success:
  - npm run coveralls
  
deploy:
  provider: heroku
  api_key: 
    secure: 4cecee06-87ac-4f60-bd9f-d24a691f4160
  app: codeshipheroku
  on:
    repo: petrovick/node-app
