language: node_js
node_js:
  - "0.12"
before_script:
  - npm install -g npm@>=2.1
  - npm install -g grunt-cli@0.1.x
  - npm install --quiet
  - npm install -g mocha
  - npm install -g istanbul
script:
  - grunt
deploy:
  provider: heroku
  api_key: 
    secure: 4cecee06-87ac-4f60-bd9f-d24a691f4160
  app: codeshipheroku
  on:
    repo: petrovick/node-app
after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive  && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
